### ISSUE TITLE
nty_poll_inner happend

### ISSUE THREAD

**Issue by juckzhang** [wangbojing/NtyCo#4]
nty_socket.c: nty_poll_inner:  Calling `nty_poll_inner` function to pass in more than one FD will cause the abort problem.

debug info:
nty_schedule_sched_wait (co=0x55555575e260, fd=6, events=28, timeout=1) at /root/clang/core/nty_schedule.c:152
152		if (co->status & BIT(NTY_COROUTINE_STATUS_WAIT_READ) ||
(gdb) n
155	            co->id, co->fd, co->status);
(gdb) 
154			printf("Unexpected event. lt id %"PRIu64" fd %"PRId32" already in %"PRId32" state\n",
(gdb) 
Unexpected event. lt id 0 fd 5 already in 9 state
156			assert(0);

stack info:
#0  nty_schedule_sched_wait (co=0x55555575e260, fd=6, events=28, timeout=1) at /root/clang/core/nty_schedule.c:156
#1  0x0000555555555fa1 in nty_poll_inner (fds=0x555555762f30, nfds=2, timeout=1) at /root/clang/sample/nty_client_mult.c:91
#2  0x0000555555556179 in init_client () at /root/clang/sample/nty_client_mult.c:134
#3  0x00005555555561bc in client (arg=0x0) at /root/clang/sample/nty_client_mult.c:143
#4  0x0000555555556360 in _exec (lt=0x55555575e260) at /root/clang/core/nty_coroutine.c:116
#5  0x0000000000000000 in ?? ()

**Comment by wangbojing** [comment]
不像是nty_poll_inner，像是汇编代码出现的问题， clang应该是不支持的。
